name: e2e-ios

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  e2e-ios:
    runs-on: macos-12
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn' # cache packages, but not node_modules
          cache-dependency-path: 'exmpl/yarn.lock'

      - name: Cache lib node modules
        uses: actions/cache@v3
        id: lib-npmcache
        with:
          path: lib/node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install lib dependencies
        if: steps.lib-npmcache.outputs.cache-hit != 'true'
        working-directory: lib
        run: yarn install

      - name: Build lib
        working-directory: lib
        run: yarn build

      - name: Cache app node modules
        uses: actions/cache@v3
        id: cache-nm
        with:
          path: exmpl/node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Rebuild detox
        if: steps.cache-nm.outputs.cache-hit == 'true'
        working-directory: exmpl
        run: yarn detox clean-framework-cache && yarn detox build-framework-cache

      - name: Install Dependencies
        if: steps.cache-nm.outputs.cache-hit != 'true'
        working-directory: exmpl
        run: yarn install && yarn rn-setup

      # - name: Activate react-native-skia-stup
      #   run: |
      #     yarn add @shopify/react-native-skia@0.1.156 git+ssh://git@github.com/limpbrains/react-native-skia-stub
      #     patch -p1 < .github/workflows/react-native-skia-stub.patch

      - name: Cache Pods
        uses: actions/cache@v3
        id: podcache
        with:
          path: exmpl/ios/Pods
          key: pods-${{ hashFiles('**/Podfile.lock') }}

      - name: Install pods
        working-directory: exmpl
        run: |
          gem update cocoapods xcodeproj
          cd ios && pod install && cd ..

      - name: Install applesimutils
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Build
        working-directory: exmpl
        run: yarn e2e:build:ios-release

      - name: Test iOS app
        working-directory: exmpl
        run: yarn e2e:test:ios-release || yarn e2e:test:ios-release || yarn e2e:test:ios-release

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: e2e-test-videos
          path: ./exmpl/artifacts/
