name: example-lint-check

on:
  pull_request:
    branches:
      - 'master'

defaults:
  run:
    working-directory: example

jobs:
  eslint:
    name: Run lint check
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v3
        id: npmcache
        with:
          path: example/node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install example dependencies
        if: steps.npmcache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Lint check
        run: yarn lint:check
